name: Run Rust Tests

on:
  push:
    branches: [main]
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu-latest
          - arch: x86_64
            distro: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-4-dev libfreetype-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --workspace -- --include-ignored